### ISSUE TITLE
Graphql & contentful locally

### ISSUE THREAD

**Issue by TarjeiB** [lucashfreitas/gatsby-monorepository-shared-theme#56]
Hey, cool project.
I tried to add my contentful details in one of the website examples but the graphql server cant find any contentful content (running start:cat). Adding the contentful plugin directly in for example website:cat works though.
Is there a setup step im missing to get contentful running from the theme?

**Comment by lucashfreitas** [comment]
Hello @TarjeiB ,

Sorry for the late reply. 

You should be able to fetch data from the shared theme, did you double check if the environment variables are correctly being passed as `themeOptions`?

**Comment by lucashfreitas** [comment]
@TarjeiB , closing this issue. Let me know if you have any other questions.
